[project]
name = "gpt-realtime-agent-long-conversation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "pydantic>=2.6.1",
]

[project.scripts]
voicebot = "realtime_voicebot.app:main"
